
vidHead = 'vid:'
titleHead = 'title:'
typeHead = 'type:'
channelHead = 'channel:'
tagHead = 'tag:'
campHead = 'lessonCamp:'
indexInCampHead = 'indexInCamp:'
wordListStart = 'wordListStart:'
wordListEnd = 'wordListEnd:'
wordItemStr='wordItemStr'